import {
  Activity,
  BarChart,
  BookMarked,
  ClipboardList,
  CreditCard,
  Database,
  FileText,
  Folder,
  FolderPlus,
  Globe,
  Key,
  LayoutGrid,
  Link,
  Link2,
  Mail,
  Megaphone,
  Plus,
  Sparkles,
  Target,
  Trophy,
  User,
  Users,
  type LucideIcon,
} from "lucide-react";

export interface NavItem {
  id: string;
  label: string;
  href: string;
  icon: LucideIcon;
  section?: string;
  title?: string;
  badge?: string;
}

export const NAV_SECTIONS: string[] = [
  "Projects",
  "Research",
  "Prospecting",
  "Prospects",
  "Agency",
  "Outreach",
  "Links",
];

export const NAV_ITEMS: NavItem[] = [
  {
    id: "command-center",
    label: "SEO Command Center",
    href: "/app/command-center",
    icon: Sparkles,
    title: "SEO Command Center",
  },
  {
    id: "projects",
    label: "All Projects",
    href: "/app/link-pro",
    icon: Folder,
    section: "Projects",
    title: "All Projects Hub",
  },
  {
    id: "create-project-wizard",
    label: "Add Project",
    href: "/app/link-pro/projects/new",
    icon: FolderPlus,
    section: "Projects",
    title: "Add Project Wizard",
  },
  {
    id: "blueprint",
    label: "Link Profiles",
    href: "/app/link-pro/projects",
    icon: Link,
    section: "Research",
    title: "Link Profiles Strategy",
  },
  {
    id: "competitors",
    label: "Competitors",
    href: "/app/link-pro/competitors",
    icon: Trophy,
    section: "Research",
    title: "Competitor Share-of-Voice",
  },
  {
    id: "keyword-prospecting",
    label: "Keyword Prospecting",
    href: "/app/link-pro/keyword-prospecting",
    icon: Key,
    section: "Prospecting",
    title: "Keyword Prospecting Finder",
  },
  {
    id: "vetted-sites",
    label: "Vetted Sites",
    href: "/app/link-pro/site-finder",
    icon: Globe,
    section: "Prospecting",
    title: "Vetted Editorial Sites Index",
  },
  {
    id: "competitor-opportunities",
    label: "Competitor Opportunities",
    href: "/app/link-pro/competitor-opportunities",
    icon: Target,
    section: "Prospecting",
    title: "Competitor Link Intersections",
  },
  {
    id: "my-list",
    label: "My List",
    href: "/app/link-pro/my-list",
    icon: Database,
    section: "Prospecting",
    title: "My Prospect Shortlists",
  },
  {
    id: "prospect-list",
    label: "Prospect List",
    href: "/app/link-pro/outreach-pipeline",
    icon: ClipboardList,
    section: "Prospects",
    title: "Prospect CRM Pipeline",
  },
  {
    id: "clients",
    label: "All Prospects",
    href: "/app/link-pro/prospects",
    icon: Users,
    section: "Prospects",
    title: "All Prospects Directory",
  },
  {
    id: "agency-clients",
    label: "Client",
    href: "/app/link-pro/agency-clients",
    icon: Users,
    section: "Agency",
    title: "Agency Client Desk",
  },
  {
    id: "campaigns",
    label: "Campaigns",
    href: "/app/link-pro/campaigns",
    icon: Megaphone,
    section: "Outreach",
    title: "Outreach Campaigns Console",
  },
  {
    id: "create-campaign",
    label: "Create Campaign",
    href: "/app/link-pro/campaigns/new",
    icon: Plus,
    section: "Outreach",
    title: "Create Outreach Campaign",
  },
  {
    id: "pitch-templates",
    label: "Pitch Templates",
    href: "/app/link-pro/pitch-templates",
    icon: FileText,
    section: "Outreach",
    title: "Pitch Templates Composer",
  },
  {
    id: "email-accounts",
    label: "Email Accounts",
    href: "/app/link-pro/email-accounts",
    icon: Mail,
    section: "Outreach",
    title: "Outreach Senders Configuration",
  },
  {
    id: "inventory",
    label: "Acquired Links",
    href: "/app/link-pro/inventory",
    icon: Link2,
    section: "Links",
    title: "Acquired Links Ledger",
  },
  {
    id: "monitoring",
    label: "Link Monitoring",
    href: "/app/link-monitor-pro",
    icon: Activity,
    section: "Links",
    title: "Link Monitoring & Crawler",
  },
  {
    id: "analytics",
    label: "Analytics Dashboard",
    href: "/app/analytics",
    icon: BarChart,
    title: "Analytics Dashboard",
  },
  {
    id: "auditor",
    label: "Blueprint Auditor",
    href: "/app/audit",
    icon: BookMarked,
    title: "Blueprint Auditor",
  },
];

// "Uprankly Tools" hub mode — shown on /app/command-center, /app/account,
// /app/billing, /app/usage, /app/team (see lib/helpers/is-link-pro-mode.ts)
export const UPRANKLY_NAV_SECTIONS: string[] = ["", "SETTINGS"];

export const UPRANKLY_NAV_ITEMS: NavItem[] = [
  {
    id: "uprankly-tools",
    label: "Uprankly Tools",
    href: "/app/command-center",
    icon: LayoutGrid,
    section: "",
    title: "SEO Command Center",
  },
  {
    id: "link-pro-hub",
    label: "Link Pro",
    href: "/app/link-pro",
    icon: Link2,
    section: "",
    title: "All Projects Hub",
  },
  {
    id: "account",
    label: "Account",
    href: "/app/account",
    icon: User,
    section: "SETTINGS",
    title: "Account & Security Profile",
  },
  {
    id: "billing",
    label: "Billing",
    href: "/app/billing",
    icon: CreditCard,
    section: "SETTINGS",
    title: "Billing & Subscriptions",
  },
  {
    id: "usage",
    label: "Usage",
    href: "/app/usage",
    icon: Activity,
    section: "SETTINGS",
    title: "Resource Usage Audits",
  },
  {
    id: "team",
    label: "Team",
    href: "/app/team",
    icon: Users,
    section: "SETTINGS",
    title: "Team Collaboration Access",
  },
];
